FROM mcr.microsoft.com/dotnet/sdk:7.0-nanoserver-ltsc2022 AS build
WORKDIR /source
COPY test-api.csproj .
RUN dotnet restore -r win10-x64 /p:PublishReadyToRun=true test-api.csproj

COPY . .
RUN dotnet publish -c release --property:PublishDir=/app -r win10-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true

FROM mcr.microsoft.com/dotnet/runtime:7.0-nanoserver-ltsc2022
COPY --from=build /app .
ENTRYPOINT ["test-api.exe"]
