@host = localhost:5176
#@host = 20.238.188.221

GET http://{{host}}/timeout
Connection: keep-alive

###

GET http://{{host}}/timeout

###

GET http://{{host}}/timeout?durationInSeconds=240&healthfailStartInSeconds=80&healthfailDurationInSeconds=80

###

GET http://{{host}}/timeout?durationInSeconds=250&healthfailStartInSeconds=80&healthfailDurationInSeconds=80

###

GET http://{{host}}/timeout?durationInSeconds=9&healthfailStartInSeconds=3&healthfailDurationInSeconds=3


###

GET http://{{host}}/timeout/health


curl -v --request GET --url 'http://20.238.188.221/timeout?durationInSeconds=250&healthfailStartInSeconds=80&healthfailDurationInSeconds=80'